# CloudFormation makefile
validate:
	echo validate started at `date`
	aws cloudformation validate-template --template-body file://vpc_sample.yaml

dist:
	echo dist started at `date`
	echo "TODO implement me"